### ISSUE TITLE
ct-ng riscv64-unknown-linux-gnu was failing at Building library

### ISSUE THREAD

**Issue by cghalibkhan** [crosstool-ng/crosstool-ng#1275]
Hi,

    I was trying to build riscv64-linux-gnu Tool-chain with this following step's:
step1 :  git clone https://github.com/crosstool-ng/crosstool-ng

step2 :  mkdir $(PWD)/crosstool-ng/Install $(PWD)/crosstool-ng/ws

step3 :  cd $(PWD)/crosstool-ng && ./bootstrap && ./configure --prefix=$(PWD)/crosstool-ng/Install && make -j4 && make -j4 install

step4 :  export PATH=$(PWD)/crosstool-ng/Install/bin:$(PATH)

step5 :  cd $(PWD)/crosstool-ng/ws/riscv64 && ct-ng riscv64-unknown-linux-gnu && ct-ng build

* All Executables build successfully, But it was failing at Build library's as follows, 

[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:39: Error: unrecognized opcode `struct clone_args{'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:40: Error: unrecognized opcode `__aligned_u64 flags'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:41: Error: unrecognized opcode `__aligned_u64 pidfd'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:42: Error: unrecognized opcode `__aligned_u64 child_tid'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:43: Error: unrecognized opcode `__aligned_u64 parent_tid'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:44: Error: unrecognized opcode `__aligned_u64 exit_signal'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:45: Error: unrecognized opcode `__aligned_u64 stack'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:46: Error: unrecognized opcode `__aligned_u64 stack_size'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:47: Error: unrecognized opcode `__aligned_u64 tls'
[ERROR]      /home/exaleap/x-tools/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/sysroot/usr/include/linux/sched.h:48: Error: junk at end of line, first unrecognized character is `}'
[ERROR]      make[4]: *** [/home/exaleap/ws/crosstool-ng/ws/riscv64/.build/riscv64-unknown-linux-gnu/build/build-libc-final/multilib/posix/vfork.os] Error 1

* can anyone Help Me to resolve this, past 4 or 5 month back it was building fine but now it was failing,
* Please Help me to over come this issue.

Thanks
Ghalib khan.

**Comment by cghalibkhan** [comment]
Hi Everyone,
                     To resolve this issue i have removed a structure declaration in a file,  /crosstool-ng/ws/riscv64/.build/src/linux-5.3.1/include/uapi/linux/sched.h .
         --> It worked !!!!!!!!!!!!!!

**Comment by lenary** [comment]
A better solution is to use a more recent version of linux 5.3 - but I'm not sure how to go about generating the checksums for this new linux version.

**Comment by cpackham** [comment]
Might be helped by #1281

**Comment by lenary** [comment]
Oh yeah, that's why I made #1281! Now I remember!

**Comment by jim-wilson** [comment]
I can try submitting a pull request if you want.

**Comment by lenary** [comment]
@jim-wilson I'm managing to build with linux 5.3.15, without hitting this issue (before, I had to apply a patch). I think they applied the patch to move the `#ifndef __ASSEMBLY__` to around the struct definitions.

**Comment by cpackham** [comment]
Sounds like relevant fixes are upstream in linux/glibc. Closing for now. Feel free to re-open if this is still a problem on 1.25.0 or master
