### ISSUE TITLE
ct-ng build of sample failure

### ISSUE THREAD

**Issue by kennethdhau** [crosstool-ng/crosstool-ng#439]
Failure at 'Installing C Library' step when attempting to build _armv6-rpi-linux-gnueabi_.  The build file included below:

[build.log.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/452914/build.log.tar.gz)

**Comment by KirillSmirnov** [comment]
gcc 6 is very strict concerning -Wparentheses.

Please, try to use glibc 2.24 for toolchain or consider the following patch:
https://sourceware.org/git/?p=glibc.git;a=commitdiff_plain;h=df1cf48777fe4cd81ad7fb09ecbe5b31432b7c1c

**Comment by kennethdhau** [comment]
glibc wasn't listed as an option (max 2.22 in ct-ng though 2.24 on the host system) and I'm having trouble installing the patch. Would you be able to recommend a resource which might help me figure out where I'm going wrong?

In case it's useful, the error when I do _git apply <patch>_:
`error: ChangeLog: No such file or directory
error: nis/nis_call.c: No such file or directory
error: stdlib/setenv.c: No such file or directory
`
(installed under pacaur in Arch Linux x86 4.7.2-1)

**Comment by KirillSmirnov** [comment]
Ungzip the attached file, put it to patches/glibc/2.22 folder and start a clean build.
The attached patch is a aforementioned patch tuned for glibc 2.22 (ChangeLog part is removed).

[200-suppress-gcc6-Wparentheses.patch.gz](https://github.com/crosstool-ng/crosstool-ng/files/464348/200-suppress-gcc6-Wparentheses.patch.gz)

**Comment by kennethdhau** [comment]
I believe I installed the patch (_/usr/lib/crosstool-ng-1.22.0/patches/glibc/2.22_) but I'm still getting the same error (-Werror=parenthesis).

**Comment by KirillSmirnov** [comment]
Hmm, that's strange. Please check build.log to be sure that the patch has been applied.
There should be smth like this:
[EXTRA]    Patching 'glibc-2.22'
<...>
[DEBUG]    ==> Executing: '/usr/bin/patch' '--no-backup-if-mismatch' '-g0' '-F1' '-p1' '-f' '-i' '/mnt/data/distr/repo/crosstool-ng-ksmirnov/patches/glibc/2.22/200-suppress-gcc6-Wparentheses.patch' 
[ALL  ]    patching file nis/nis_call.c
[ALL  ]    patching file stdlib/setenv.c


Alternatively you may want to try the latest crosstool-ng snapshot. The corresponding fixes for gcc6/glibc2.23 have been applied today. Note that glibc 2.22 won't work in this case, only 2.23

**Comment by kennethdhau** [comment]
The build.log should be below:
[snp.build.log.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/464705/snp.build.log.tar.gz)

I didn't see anything in the log that seemed to apply the patch, though.  Is there something that I may not be enabling in the config file?

**Comment by KirillSmirnov** [comment]
The patch has not been applied since ct-ng has already passed the stage "patching glibc":
[DEBUG]    Already extracted 'gcc-5.2.0'
[DEBUG]    Already patched 'gcc-5.2.0'
[DEBUG]    Already extracted 'glibc-2.22'
[DEBUG]    Entering '/home/kenneth/workspace/toolchain/.build/src/glibc-2.22'
[DEBUG]    Already patched 'glibc-2.22'

Please make a clean build. I mean, delete directory '.build' and try again.

**Comment by kennethdhau** [comment]
It no longer seems to have a problem with Werror-parenthesis but I'm still getting build issues. Should I open a new issue or continue here?

**Comment by KirillSmirnov** [comment]
I think continuing here is OK, since the sample still fails.

**Comment by kennethdhau** [comment]
[build.log.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/464766/build.log.tar.gz)
_../sysdeps/unix/sysv/linux/dl-openat64.c:26:1: error: 'openat64' defined as variadic function without prototype [-Werror]_
I'm getting the error in Build C Library localdef. Should I upload my configuration file as well?

**Comment by KirillSmirnov** [comment]
Oh, my. After investigation it became clear that Glibc 2.22 is very old for gcc 6. Disabling CT_LIBC_LOCALES option might help.

The configuration is embedded into build.log, so there is no need to make a separate attach right now.

**Comment by kennethdhau** [comment]
I set it to 'n' but it still appears to bug at the same step

**Comment by KirillSmirnov** [comment]
Clean build? localedef should not be built unless CT_LIBC_LOCALES is set.

**Comment by kennethdhau** [comment]
That worked - another error has appeared though.

[build.log.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/464962/build.log.tar.gz)

**Comment by KirillSmirnov** [comment]
Now this is issue #437 - there are some instructions how to fix it.

I think the most efficient way is to try a fresh crosstool-ng, it fully supports building with gcc 6.

**Comment by kennethdhau** [comment]
Okay, thank you for all of the help!
