### ISSUE TITLE
Canadian cross in cygwin fails install kernel headers step.

### ISSUE THREAD

**Issue by andrimarjonsson** [crosstool-ng/crosstool-ng#97]
It seems the canadian cross setup under cygwin has stopped working in both 1.20.0 and 1.21.0.
The process fails in the Install Kernel Header section with the following error message:

> .../tools/include/tools/le_byteshift.h:4:25: fatal error: linux/types.h: No such file or directory

I've currently tried various versions of kernel headers along with providing a custom kernel source directory to no avail.

Canadian setup is as follows:
 * build  = i686-pc-cygwin
 * host   = i686-pc-mingw32
 * target = x86_64-pc-linux-gnu

Full build log and config can be found here: https://gist.github.com/andrimarjonsson/ba730dde1e4ff51b23e1

**Comment by mingwandroid** [comment]
I get "Error: blob too big" when trying to download your build.log. I've tried various approaches and none have worked. Can you upload just the last few k?

**Comment by bhundven** [comment]
same as @mingwandroid

**Comment by andrimarjonsson** [comment]
Updated the gist URL in the original post. Now only includes the tail of the build log plus the config. Should be viewable now. Please let me know if you need any more info.

**Comment by bhundven** [comment]
@mingwandroid Can you or @diorcety take a look at this?

**Comment by mingwandroid** [comment]
Sure.

**Comment by mingwandroid** [comment]
This should be fixed now. I will wait until the 1.22 release to close.

**Comment by mingwandroid** [comment]
This is fixed, but you must follow the documentation at:

https://github.com/crosstool-ng/crosstool-ng/blob/master/docs/C%20-%20Misc.%20tutorials.txt#L317-L361

I added a sample for x86_64 but it should apply just as well for i686 (modulo DLL rebase issues you may run into .. if your build machine is a 64-bit computer then you should use:

 * build  = x86_64-pc-cygwin
 * host   = i686-w64-mingw32
 * target = x86_64-pc-linux-gnu

Things to note above:
1. "i686" becomes "x86_64" for build
2. "pc" becomes "w64" for host (this is since dropping mingw.org in favor of mingw-w64)
