### ISSUE TITLE
Issue with compiling Sh4 with gcc 11.1

### ISSUE THREAD

**Issue by MOHAMED19OS** [crosstool-ng/crosstool-ng#1509]
I did compiled latest crosstool-ng from master.
Crosstool-NG was compiled on: `5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux`

`[ERROR]      collect2: error: ld returned 1 exit status
[ERROR]      make[3]: *** [Makefile:341: /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/elf/librtld.map] Error 1
[ERROR]      make[3]: *** Waiting for unfinished jobs....
[ERROR]      make[2]: *** [Makefile:214: elf/subdir_lib] Error 2
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@400]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1608]
[ERROR]  >>        called from: glibc_backend[scripts/build/libc/glibc.sh@74]
[ERROR]  >>        called from: glibc_main[scripts/build/libc/glibc.sh@44]
[ERROR]  >>        called from: do_libc_main[scripts/build/libc.sh@33]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@695]
[ERROR]  >>
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 16:41.60)
[16:42] / make: *** [ct-ng:261: build] Error 2
`

[build_log.zip](https://github.com/crosstool-ng/crosstool-ng/files/6472099/build_log.zip)
[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/6472104/config.zip)

**Comment by cpackham** [comment]
The error is

```
[ALL  ]      sh4-FoReVeR-linux-gnu-gcc  -g -O2 -U_FORTIFY_SOURCE       -nostdlib -nostartfiles -r -o /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/libc_pic.os  -Wl,-d -Wl,--whole-archive /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/libc_pic.a -o /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/libc_pic.os
[ALL  ]      sh4-FoReVeR-linux-gnu-gcc  -g -O2 -U_FORTIFY_SOURCE       -nostdlib -nostartfiles -r -o /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/elf/librtld.map.o '-Wl,-(' /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/elf/dl-allobjs.os /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/libc_pic.a -lgcc '-Wl,-)' -Wl,-Map,/home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/elf/librtld.mapT
[ALL  ]      /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/buildtools/lib/gcc/sh4-FoReVeR-linux-gnu/11.1.0/../../../../sh4-FoReVeR-linux-gnu/bin/ld: /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/libc_pic.a(init-first.os):/home/mohamed/crosstool-ng/.build/src/glibc-2.23/csu/init-first.c:34: multiple definition of `__libc_multiple_libcs'; /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/elf/dl-allobjs.os:/home/mohamed/crosstool-ng/.build/src/glibc-2.23/elf/../elf/dl-sysdep.c:58: first defined here
[ALL  ]      /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/buildtools/lib/gcc/sh4-FoReVeR-linux-gnu/11.1.0/../../../../sh4-FoReVeR-linux-gnu/bin/ld: /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/libc_pic.a(_itoa.os): in function `_itoa':
[ALL  ]      /home/mohamed/crosstool-ng/.build/src/glibc-2.23/stdio-common/_itoa.c:196: multiple definition of `_itoa'; /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/elf/dl-allobjs.os:/home/mohamed/crosstool-ng/.build/src/glibc-2.23/elf/dl-minimal.c:329: first defined here
[ERROR]      collect2: error: ld returned 1 exit status
[ERROR]      make[3]: *** [Makefile:341: /home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib/elf/librtld.map] Error 1
[ERROR]      make[3]: *** Waiting for unfinished jobs....
[ALL  ]      make[3]: Leaving directory '/home/mohamed/crosstool-ng/.build/src/glibc-2.23/elf'
[ERROR]      make[2]: *** [Makefile:214: elf/subdir_lib] Error 2
[ALL  ]      make[2]: Leaving directory '/home/mohamed/crosstool-ng/.build/src/glibc-2.23'
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
[ALL  ]      make[1]: Leaving directory '/home/mohamed/crosstool-ng/.build/sh4-FoReVeR-linux-gnu/build/build-libc-final/multilib'
```

No clue what the actual problem is. It may be that the bleeding edge gcc is simply not compatible with the older glibc.

**Comment by cpackham** [comment]
I see the same error building `sh-multilib-linux-gnu` and changing the libc version to glibc-2.23. Builds fine with glibc-2.33.

**Comment by MOHAMED19OS** [comment]
but if use the glibc-2.33 the Toolchain not work in receiver

I will downgrade the Gcc and test
