### ISSUE TITLE
build fails on mac

### ISSUE THREAD

**Issue by karfield** [crosstool-ng/crosstool-ng#284]
I copied arm-none-linux-gnueabi example to build on my Mac (xcode version is 7.1.1, the latest)
but fails as building binutils:

[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:51:72: error: use of undeclared identifier 'do_not_use_isalnum_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:59:72: error: use of undeclared identifier 'do_not_use_isalpha_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:75:72: error: use of undeclared identifier 'do_not_use_iscntrl_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:83:72: error: use of undeclared identifier 'do_not_use_isdigit_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:91:72: error: use of undeclared identifier 'do_not_use_isgraph_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:99:72: error: use of undeclared identifier 'do_not_use_islower_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:107:72: error: use of undeclared identifier 'do_not_use_isprint_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:115:72: error: use of undeclared identifier 'do_not_use_ispunct_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:123:72: error: use of undeclared identifier 'do_not_use_isspace_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:131:72: error: use of undeclared identifier 'do_not_use_isupper_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:139:73: error: use of undeclared identifier 'do_not_use_isxdigit_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:147:72: error: use of undeclared identifier 'do_not_use_tolower_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:155:72: error: use of undeclared identifier 'do_not_use_toupper_with_safe_ctype'
[ERROR]    make[5]: *** [binary.o] Error 1
[ERROR]    make[4]: *** [all-recursive] Error 1
[ERROR]    make[3]: *** [all] Error 2
[ERROR]    make[2]: *** [all-gold] Error 2
[ERROR]    make[1]: *** [all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@216]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@240]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@105]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/share/doc/crosstool-ng/crosstool-ng-1.22.0-2-gead1358-dirty/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 8:25.92)
[08:26] / make: *** [build] Error 1

**Comment by bhundven** [comment]
This is a duplicate of #211. Closing.
