### ISSUE TITLE
Build failed in Ubuntu 15.04. Message: Build failed in step 'Installing PPL for host'

### ISSUE THREAD

**Issue by josancardenasm** [crosstool-ng/crosstool-ng#138]
Hello, i'm trying to build with crosstool-ng versión 1.19.0. 
i have the message "Build failed in step 'Installing PPL for host'"

What is the problem?
```
[ALL  ]    In file included from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator_System.defs.hh:27:0,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.defs.hh:28,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.cc:25:
[ERROR]    /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Generator_System.defs.hh:253:7: error: 'ptrdiff_t' was not declared in this scope
[ALL  ]           ptrdiff_t,
[ALL  ]           ^
[ALL  ]    /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Generator_System.defs.hh:253:7: note: suggested alternatives:
[ALL  ]    In file included from /usr/include/c++/4.9/iostream:38:0,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/checked.defs.hh:26,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Checked_Number.defs.hh:27,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Coefficient.types.hh:15,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Coefficient.defs.hh:26,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.defs.hh:27,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.cc:25:
[ALL  ]    /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
[ALL  ]       typedef __PTRDIFF_TYPE__ ptrdiff_t;
[ALL  ]                                ^
[ALL  ]    /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
[ALL  ]    In file included from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator_System.defs.hh:27:0,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.defs.hh:28,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.cc:25:
[ERROR]    /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Generator_System.defs.hh:255:23: error: template argument 3 is invalid
[ALL  ]           const Generator&> {
[ALL  ]                           ^
[ALL  ]    In file included from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.defs.hh:28:0,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.cc:25:
[ERROR]    /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator_System.defs.hh:268:7: error: 'ptrdiff_t' was not declared in this scope
[ALL  ]           ptrdiff_t,
[ALL  ]           ^
[ALL  ]    /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator_System.defs.hh:268:7: note: suggested alternatives:
[ALL  ]    In file included from /usr/include/c++/4.9/iostream:38:0,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/checked.defs.hh:26,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Checked_Number.defs.hh:27,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Coefficient.types.hh:15,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Coefficient.defs.hh:26,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.defs.hh:27,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.cc:25:
[ALL  ]    /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
[ALL  ]       typedef __PTRDIFF_TYPE__ ptrdiff_t;
[ALL  ]                                ^
[ALL  ]    /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
[ALL  ]    In file included from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.defs.hh:28:0,
[ALL  ]                     from /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator.cc:25:
[ERROR]    /home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/src/ppl-0.10.2/src/Grid_Generator_System.defs.hh:270:28: error: template argument 3 is invalid
[ALL  ]           const Grid_Generator&>,
[ALL  ]                                ^
[ALL  ]    Makefile:1032: recipe for target 'Grid_Generator.lo' failed
[ERROR]    make[4]: *** [Grid_Generator.lo] Error 1
[ALL  ]    make[4]: *** Waiting for unfinished jobs....
[ALL  ]    mv -f .deps/Coefficient.Tpo .deps/Coefficient.Plo
[ALL  ]    mv -f .deps/Init.Tpo .deps/Init.Plo
[ALL  ]    mv -f .deps/Linear_Expression.Tpo .deps/Linear_Expression.Plo
[ALL  ]    make[4]: Leaving directory '/home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/arm-unknown-linux-uclibcgnueabi/build/build-ppl-host-x86_64-build_pc-linux-gnu/src'
[ALL  ]    Makefile:851: recipe for target 'all' failed
[ERROR]    make[3]: *** [all] Error 2
[ALL  ]    make[3]: Leaving directory '/home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/arm-unknown-linux-uclibcgnueabi/build/build-ppl-host-x86_64-build_pc-linux-gnu/src'
[ALL  ]    Makefile:415: recipe for target 'all-recursive' failed
[ERROR]    make[2]: *** [all-recursive] Error 1
[ALL  ]    make[2]: Leaving directory '/home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/arm-unknown-linux-uclibcgnueabi/build/build-ppl-host-x86_64-build_pc-linux-gnu'
[ALL  ]    Makefile:343: recipe for target 'all' failed
[ERROR]    make[1]: *** [all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/goonie/practicas/02_Toolchain/crosstool-ng-1.19.0/.build/arm-unknown-linux-uclibcgnueabi/build/build-ppl-host-x86_64-build_pc-linux-gnu'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing PPL for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_ppl_backend[scripts/build/companion_libs/120-ppl.sh@128]
[ERROR]  >>        called from: do_ppl_for_host[scripts/build/companion_libs/120-ppl.sh@78]
[ERROR]  >>        called from: do_companion_libs_for_host[scripts/build/companion_libs.sh@36]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@632]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 3:09.34)
```

**Comment by josancardenasm** [comment]
i have installed the last version of crosstool-ng and the problem has been solved.
