### PR TITLE
Add gcc 9.3 and 10.2, and binutils 2.35

### PR DESCRIPTION
**Pull request by egtvedt**
Updated pull request of #1338, now also adding GCC 10.1.0 as requested by @galak.

### CODE REVIEW

**Comment by graysky2** [comment]
thanks for this, @egtvedt!

**Comment by realPy** [comment]
works great thanks @egtvedt

**Review by cpackham — APPROVED** [review]

**Review by cpackham — APPROVED** [review]
Oddly enough the first mirror I checked http://www.netgull.com/gcc/releases/ didn't have gcc-10.2.0 all the others I spot checked do.

**Comment by cpackham** [comment]
I'll get to merging this PR shortly. I wanted to get the CI stuff sorted first. I'll also do a few builds locally for the new GCC version.

**Comment by cpackham** [comment]
The first build I tried (`arm-unknown-linux-gnueabi`) ran into the following error
```
[INFO ]  Installing pass-2 core C gcc compiler: done in 164.65s (at 09:33)
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      ../sysdeps/ieee754/dbl-64/s_modf.c:84:28: error: conflicting types for built-in function 'modfl'; expected 'long double(long double,  long double *)' [-Werror=builtin-declaration-mismatch]
[ERROR]      make[3]: *** [/home/x-tool/.build/arm-unknown-linux-gnueabi/build/build-libc-final/multilib/sysd-rules:553: /home/x-tool/.build/arm-unknown-linux-gnueabi/build/build-libc-final/multilib/math/s_modf.o] Error 1
[ERROR]      make[3]: *** Waiting for unfinished jobs....
[ERROR]      make[2]: *** [Makefile:470: math/subdir_lib] Error 2
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
```

**Comment by egtvedt** [comment]
Interesting, I will have a go at the 32-bit ARM toolchain.

**Comment by realPy** [comment]
This work for an aarch64 for me

**Comment by egtvedt** [comment]
I can also build Aarch64, but 32-bit ARM does in fact not build with GCC 10.2 and binutils 2.35. I will see if I can figure out why.

**Comment by egtvedt** [comment]
Think we need a patch from GCC upstream, http://patchwork.ozlabs.org/project/gcc/patch/96819cd6-2bef-a056-6476-a55c6e72fe30@gmail.com/

**Comment by egtvedt** [comment]
https://sourceware.org/pipermail/glibc-cvs/2020q1/069150.html this is probably the appropriate fix.

**Comment by egtvedt** [comment]
Building with glibc 2.32 has this patch included, all glibc prior to 2.31 requires this patch.

**Comment by cpackham** [comment]
https://sourceware.org/git?p=glibc.git;a=patch;h=49348beafe9ba150c9bd48595b3f372299bddbb0

**Comment by egtvedt** [comment]
@cpackham what glibc versions do you feel are appropriate to backport patch to? 2.30 and 2.31?

I can do a build test with glibc 2.31, and see how fart the patch easily applies backwards?

**Comment by cpackham** [comment]
Add the patch for 2.31 and see how cleanly the patch applies to any others. If you rebase your series against master you'll get the CI builds to test things out.

**Comment by egtvedt** [comment]
@cpackham glibc was straightforward to patch from glibc 2.27 and newer, I have forced pushed an updated branch.

**Review by cpackham — APPROVED** [review]

**Comment by cpackham** [comment]
Thanks. I'll look at merging this over the weekend.
