### PR TITLE
Update to gcc 9.2.0

### PR DESCRIPTION
**Pull request by egtvedt**
Forward ported patches from GCC 8.3.0 to 9.2.0, refreshed to match
current sources.

In patch 0012-crystax.patch, removed changing sysv4.h header file for
rs6000, since it no longer defines LINK_EH_SPEC.

Removed the following patches because they are part of upstream:
- 0018-ARC-Add-multilib-support-for-linux-targets.patch
- 0020-ARM-fix-cmse.patch
- 0021-arm-Make-arm_cmse.h-C99-compatible.patch
- 0022-ARC-Update-fma-expansions.patch

Renamed 0019-isl-0.20.patch => 0018-isl-0.20.patch.

Signed-off-by: Hans-Christian Noren Egtvedt <hegtvedt@cisco.com>

### CODE REVIEW

**Comment by engstk** [comment]
arm64 cross build went good on my Ubuntu server 18.04.3 with:
binutils-2.32
bison-3.3.2
expat-2.2.6
gcc-9.2.0
gdb-8.2.1
gettext-0.19.8.1
glibc-2.28
gmp-6.1.2
isl-0.20
libiconv-1.15
linux-4.14.99
mpc-1.1.0
mpfr-4.0.2
ncurses-6.1


Had the same error you had on Ubuntu 19.04 with glibc-2.29:
`[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      ../sysdeps/aarch64/sfp-machine.h:50:31: error: '_FPU_FPCR_RM_MASK' undeclared (first use in this function)
`

Since Ubuntu 18.04.3 has some backports from 19.04, I mst have caught the regression you had earlier on the gcc-9.1.0 pull.

I tried with latest stable glibc-2.30, build goes nicely, so it must have been fixed somewhere upstream.

**Comment by egtvedt** [comment]
@engstk I build glibc 2.29 HEAD of the release branch, and that compiles fine on Ubuntu 19.04, hence I suspect glibc has done some fixes since the initial 2.29 release.

Have not skimmed through the history for relevant commits.

**Comment by engstk** [comment]
That may be the case, the snapshot of glibc-2.29 in ct-ng triggers it for sure.
Maybe they backport 2.30 to 2.29 head.
Appart from that, all good here, already using in production.

**Comment by egtvedt** [comment]
The undeclared _FPU_FPCR_RM_MASK is a bit weird when digging into it, since it is defined in
sysdeps/aarch64/fpu/fpu_control.h:#define _FPU_FPCR_RM_MASK  0xc00000

Also, then offending sysdeps/aarch64/sfp-machine.h file will do an include fpu_control.h at top.

**Comment by smagellan** [comment]
@egtvedt, thank you,  works good for stm32f4
