### PR TITLE
Update to gcc 9.1.0

### PR DESCRIPTION
**Pull request by egtvedt**
Forward ported patches from GCC 8.3.0 to 9.1.0, refreshed to match
current sources.

In patch 0012-crystax.patch, removed changing sysv4.h header file for
rs6000, since it no longer defines LINK_EH_SPEC.

Removed the following patches because they are part of upstream:
- 0018-ARC-Add-multilib-support-for-linux-targets.patch
- 0020-ARM-fix-cmse.patch
- 0021-arm-Make-arm_cmse.h-C99-compatible.patch
- 0022-ARC-Update-fma-expansions.patch

Renamed 0019-isl-0.20.patch => 0018-isl-0.20.patch.

Signed-off-by: Hans-Christian Noren Egtvedt <hegtvedt@cisco.com>

### CODE REVIEW

**Comment by egtvedt** [comment]
Note not very thorough testing yet on any architecture. Will test ARM builds on both 32-bit and 64-bit.

**Comment by smagellan** [comment]
Nice. I was able to build opencm3 lcd-dma demo and flash stm32f429i-disc1 with it.

**Comment by egtvedt** [comment]
32-bit ARM build worked for me, but 64-bit ARM did not compile. Have not looked into the problem yet, most likely trivial.

**Comment by engstk** [comment]
arm64 build worked nicely for me on LM 19.1

**Comment by egtvedt** [comment]
@engstk thank you for testing on Aarch64, I am on Ubuntu 19.04, but I suspect the problem is a combination of my crosstool-ng configuration. Have not had time to dig further into the problem, hopefully I will find some time this week.

**Comment by engstk** [comment]
@egtvedt Yeah maybe is somethign particular to your config.

I also build on my Ubuntu 18.04.2 server, with latest tools and components:
binutils-2.32.tar.xz
bison-3.3.2.tar.xz
expat-2.2.6.tar.bz2
gcc-9.1.0.tar.xz
gdb-8.2.1.tar.xz
gettext-0.19.8.1.tar.xz
glibc-2.29.tar.xz
gmp-6.1.2.tar.xz
isl-0.20.tar.xz
libiconv-1.15.tar.gz
linux-4.9.156.tar.xz
mpc-1.1.0.tar.gz
mpfr-4.0.2.tar.xz
ncurses-6.1.tar.gz

I encountered some hiccups in previous gcc builds with glibc 2.29 from time to time in some systems and dropped to 2.26.
The latest build I tried with 2.29 also finished nicely on my Ubuntu LTS build box.
Already using it on production.

**Comment by egtvedt** [comment]
@engstk Sounds very promising. I am buildinig using Linux 4.4.y, which might be related to the build problem I experience. It looks to be header related, will try to upgrade to latest Linux stable.

**Comment by egtvedt** [comment]
Just a minor update, I can build an Aarch64 toolchain on CentOS 7.6, but not on Ubuntu 19.04.

Errors out with
```
[EXTRA]      Building C library
[ERROR]      ../sysdeps/aarch64/sfp-machine.h:50:31: error: '_FPU_FPCR_RM_MASK' undeclared (first use in this function)
```

I will anyway wait for GCC 9.2.0 and refresh til pull request as there are too many bugfixes IMHO to make fully use of GCC 9.1.0.

**Comment by fidomax** [comment]
Is there any news?

**Comment by smagellan** [comment]
gcc-9.2 has arrived: https://www.phoronix.com/scan.php?page=news_item&px=GCC-9.2-Released

**Comment by egtvedt** [comment]
I will redo the request with a GCC 9.2.0 update instead.

**Comment by egtvedt** [comment]
@smagellan see issue #1223
